syntax = "proto3";

package GrpcHardwareMonitor;

message Sensor {
    enum SensorType {        
        Voltage = 0;
        Current = 1;
        Power = 2; 
        Clock = 3; 
        Temperature = 4;  
        Load = 5; 
        Frequency = 6;  
        Fan = 7;  
        Flow = 8;  
        Control = 9; 
        Level = 10;  
        Factor = 11; 
        Data = 12;  
        SmallData = 13;  
        Throughput = 14; 
        TimeSpan = 15; 
        Energy = 16;  
        Noise = 17;  
        Conductivity = 18; 
        Humidity = 19;
        Unknown = 20;
    };
    SensorType type = 1;
	string name = 2;
    optional float value = 3;  
    optional float min = 4;  
    optional float max = 5;         
}

message Hardware {
    enum HardwareType {        
        Cpu = 0;
        GpuNvidia = 1;
        GpuAmd = 2;
        GpuIntel = 3;
        Storage = 4;
        Memory = 5;
        Unknown = 6;
    };
    HardwareType type = 1;
    string name = 2;
    repeated Sensor sensors = 3;
}

message HardwareStructure {
    repeated Hardware hardwares = 1;
}

message SensorInfo {
    string hardwareName = 1;
    string sensorName = 2;
	optional float value = 3;
}

message None {}

service HardwareService {
    rpc checkAuthentication(None) returns (None) {}
    rpc getHardwareStructure(None) returns (HardwareStructure) {}	 
    rpc getSensorStream(None) returns (stream SensorInfo){}
}
